'use client';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faPlay,
    faBook,
    faCode,
    faPuzzlePiece,
    faLightbulb,
    faArrowRight,
    faArrowLeft,
    faChevronRight,
    faChevronDown,
    faChevronUp,
    faGraduationCap,
    faMobile,
    faLaptopCode,
    faChartLine,
    faCircleCheck,
    faEllipsis,
    faArrowDown,
    faServer,
    faDatabase,
    faNetworkWired,
    faCloud,
    faShieldHalved,
    faBolt,
    faGears,
    faCubes,
    faLayerGroup,
    faDiagramProject,
    faGlobe,
    faEnvelope,
    faHeart,
    faSun,
    faMoon,
    faBars,
    faXmark,
} from '@fortawesome/free-solid-svg-icons';

import {
    faWhatsapp,
    faJs,
    faPython,
    faReact,
    faNode,
    faTwitter,
    faGithub,
    faLinkedin,
    faYoutube,
} from '@fortawesome/free-brands-svg-icons';

// Add all icons to the library
library.add(
    faPlay,
    faBook,
    faCode,
    faPuzzlePiece,
    faLightbulb,
    faArrowRight,
    faArrowLeft,
    faChevronRight,
    faChevronDown,
    faChevronUp,
    faGraduationCap,
    faMobile,
    faLaptopCode,
    faChartLine,
    faCircleCheck,
    faEllipsis,
    faArrowDown,
    faServer,
    faDatabase,
    faNetworkWired,
    faCloud,
    faShieldHalved,
    faBolt,
    faGears,
    faCubes,
    faLayerGroup,
    faDiagramProject,
    faGlobe,
    faEnvelope,
    faHeart,
    faSun,
    faMoon,
    faBars,
    faXmark,
    faWhatsapp,
    faJs,
    faPython,
    faReact,
    faNode,
    faTwitter,
    faGithub,
    faLinkedin,
    faYoutube,
);

export { FontAwesomeIcon };
